# Generated by Django 5.2.3 on 2025-06-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter department name', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter employee name', max_length=100)),
                ('email', models.EmailField(help_text='Enter email', max_length=255, unique=True)),
                ('phone_number', models.IntegerField(help_text='Enter phone number', unique=True)),
                ('address', models.CharField(help_text='Enter address', max_length=255)),
                ('date_of_joining', models.DateField(help_text='Enter date of joining')),
                ('department', models.ForeignKey(help_text='Enter department', on_delete=django.db.models.deletion.CASCADE, to='company.department')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Enter date')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], help_text='Enter status(Present/Absent/Late)', max_length=7)),
                ('employee', models.ForeignKey(help_text='Enter employee(FK)', on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Enter performance rating(1-5)')),
                ('review_date', models.DateField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Enter review date')),
                ('employee', models.ForeignKey(help_text='Enter employee(FK)', on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
            ],
        ),
    ]
